spring:
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/auth_db}
    username: ${SPRING_DATASOURCE_USERNAME:order_user}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
#  kafka:
#    bootstrap-servers: localhost:9094
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      acks: all
#      retries: 3
#      properties:
#        enable.idempotence: true
#        max.in.flight.requests.per.connection: 5
#        spring.json.type.mapping: "userCreatedEvent:click.pavlomoskalenko.auth.messaging.event.UserCreatedEvent"
security:
  jwt:
    access_token_expiration: 900000
    refresh_token_expiration: 86400000
server:
  servlet:
    context-path: /api
