spring:
  application:
    name: order-system
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver

security:
  jwt:
    secret_key: ${JWT_SECRET_KEY}
    access_token_expiration: 900000
    refresh_token_expiration: 86400000