
spring:
  application:
    name: order-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/order_db}
    username: ${SPRING_DATASOURCE_USERNAME:order_user}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:8080/api/.well-known/jwks.json
#  kafka:
#    bootstrap-servers: localhost:9094
#    consumer:
#      group-id: order-service
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      enable-auto-commit: false
#      properties:
#        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#        spring.json.trusted.packages: "click.pavlomoskalenko.order"
#        spring.json.type.mapping: "userCreatedEvent:click.pavlomoskalenko.order.messaging.event.UserCreatedEvent"
#    listener:
#      ack-mode: manual
server:
  port: 8081
