#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://auth-service:8080/api/.well-known/jwks.json
#  kafka:
#    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
server:
  port: 8080
